"use client";
import { useState, type FormEvent } from "react";
import type { SupabaseClient } from "@supabase/supabase-js";
import { ArrowLeft, ArrowRight, CheckCircle2, ChevronRight, Clock3, Copy, Home, KeyRound, Link2, ListChecks, LoaderCircle, Mail, Plus, QrCode, ReceiptText, Search, Settings2, ShoppingBasket, SlidersHorizontal, UserRound, Users, WalletCards, X } from "lucide-react";
import type { ActivityLog, Bill, Debt, DebtAdjustment, EventTag, House, HouseEvent, HouseMember, HousePermissions, HouseSection, Invite, PendingInvite, PermissionLevel, PermissionSection, Profile, ShoppingItem, Task, Theme } from "@/types/homehq";

export function CreateTaskPage({ house, members, supabase, onBack, onCreated }: { house: House; members: HouseMember[]; supabase: SupabaseClient; onBack: () => void; onCreated: () => void }) {
  const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [frequency, setFrequency] = useState(""); const [dueAt, setDueAt] = useState(""); const [assignees, setAssignees] = useState<string[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  function toggleAssignee(id: string) { setAssignees((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]); }
  async function createTask(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setError(""); setLoading(true);
    const { error: createError } = await supabase.rpc("create_house_task", { target_house_id: house.id, task_title: title, task_description: description || null, task_frequency: frequency, task_next_due_at: new Date(dueAt).toISOString(), assignee_ids: assignees });
    if (createError) { setError(createError.message); setLoading(false); return; }
    await onCreated();
  }
  return <div className="create-bill-page"><button className="back-button" onClick={onBack}><ArrowLeft size={18} /> Tarefas</button><div className="house-page-heading"><div><span className="eyebrow">Nova tarefa</span><h1>Organizar tarefa</h1><p>Escolhe o prazo, periodicidade e um ou vários responsáveis.</p></div></div><form className="bill-form" onSubmit={createTask}><div className="bill-fields"><label>Título<span className="input-wrap"><ListChecks size={18} /><input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Ex: Limpar a cozinha" required /></span></label><label>Periodicidade<select value={frequency} onChange={(event) => setFrequency(event.target.value)} required><option value="" disabled>Periodicidade da tarefa</option><option value="daily">Diária</option><option value="weekly">Semanal</option><option value="monthly">Mensal</option><option value="one_time">Única</option></select></label><label>Data e hora limite<input className="plain-input" type="datetime-local" value={dueAt} onChange={(event) => setDueAt(event.target.value)} required /></label><label>Descrição<input className="plain-input" value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Opcional" /></label></div><div className="assignee-picker"><strong>Responsáveis</strong><div>{members.map((member) => <label key={member.user_id} className={assignees.includes(member.user_id) ? "selected" : ""}><input type="checkbox" checked={assignees.includes(member.user_id)} onChange={() => toggleAssignee(member.user_id)} /><span className="member-avatar">{member.username.slice(0, 1).toUpperCase()}</span>{member.username}</label>)}</div></div>{error && <p className="feedback error">{error}</p>}<button className="primary-button" disabled={loading || assignees.length === 0}>{loading ? <LoaderCircle className="spin" size={19} /> : <>Guardar tarefa<ArrowRight size={18} /></>}</button></form></div>;
}
